version: '3.5'

services:
  kong-database:
    image: postgres:10.1-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
     - POSTGRES_USER=kong
     - POSTGRES_DB=kong
    volumes:
     - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  kong-server:
    image: kong:0.12.1
    depends_on:
      - kong-database
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8001
        - traefik.frontend.rule=Host:api.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
        - traefik.docker.network=traefik-net
    volumes:
     - ./kong/:/etc/kong/
    environment:
     - KONG_DATABASE=postgres 
     - KONG_PG_HOST=kong-database
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:8000 || exit 1"]
      interval: 5s
      retries: 10
  
  dashboard:
    image: pgbi/kong-dashboard:v3.1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:apidashboard.services.alin.be
        - traefik.frontend.entryPoints=http,https
    command: "start --kong-url http://kong-server"

  stat:
    image: kamon/grafana_graphite:3.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
       - traefik.port=80
        - traefik.frontend.rule=Host:apistat.services.alin.be
        - traefik.backend=apistat
        - traefik.frontend.entryPoints=http,https
    volumes:
     - ./grafana/data:/opt/grafana/data

#networks:
#  default:
#    external:
#      name: traefik-net
